### ISSUE TITLE
Trisomy 21 and Turner references missing

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/growth-references#1]
To implement these references we need the tables

**Comment by statist7** [comment]
Here are Excel files with LMS tables for Down syndrome and Turner syndrome. The former is a publication of mine (though we need to check the copyright with the Down syndrome SIG at the College) while the latter is extracted from a paper by Lyon et al.
[LMS_Downs.xlsx](https://github.com/rcpch/growth-references/files/5475332/LMS_Downs.xlsx)
[Turner_syndrome_LMS_Lyon.xlsx](https://github.com/rcpch/growth-references/files/5475333/Turner_syndrome_LMS_Lyon.xlsx)
