### ISSUE TITLE
Is Reference Interchange Format (RIF) an option?

### ISSUE THREAD

**Issue by stefvanbuuren** [rcpch/growth-references#3]
Hi, would the RIF format as used in 

<https://github.com/growthcharts/centile/tree/master/data-raw/data/who>
<https://growthcharts.org/centile/articles/articles/rif.html>

be helpful for storing your references?

**Comment by eatyourpeas** [comment]
Thank you for this suggestion. I'm not familiar with RIF format but happy to learn. We have hitherto stored the references as JSON - it feels safer to me as there are key: value pairs to protect against indexing errors etc. JSON also is the linguafranca of information exchange between APIs and here to stay. I am open to the idea that we store the data in multiple different formats which would allow users with different preferences to access. If you have any guidance on this or would like to submit a pull request we would be glad to look at it.
@statist7 may also have a view.

**Comment by stefvanbuuren** [comment]
Thanks. I think it is useful to have both formats. It would also be convenient if we can easily convert between them.

Plain text RIF would appeal to creators of references who want to make their results available to the wider community, and to users of references who want to do their own calculations. The JSON version would be the way to exchange references between API's.

If you have a pointer to your current JSON version, perhaps we could then identify overlap.

**Comment by eatyourpeas** [comment]
The references are [here](https://github.com/rcpch/rcpchgrowth-python/tree/live/rcpchgrowth/data_tables). The RCPCHGrowth-python repository contains a python package which does all the maths. It is imported as a dependency to the API server. 
This repository is intended to house references from across the world for general use and interest. At them moment it is a short list but in time with collaboration with others it is hoped it will grow. 
if you were happy to help convert existing references to RIF format I would be very grateful. Is it a process that could be automated?

**Comment by stefvanbuuren** [comment]
We may load in `R` both versions of the WHO male infant as follows:

```r
library(jsonlite)
json <- fromJSON("https://raw.githubusercontent.com/rcpch/rcpchgrowth-python/live/rcpchgrowth/data_tables/who_infants.json")
head(json$measurement$height$male)

remotes::install_github("growthcharts/centile")
library(centile)
rif <- load_reference("who_2006_hgt_male_")
head(rif)
rif[rif$x %in% c(0.0383, 0.0575), ]
```

This quick comparison confirms that we're (fortunately) looking at the same references. Some observations:

- The age grids differ. But both format easily accommodate for that;
- In RIF, we have one distribution per file. The JSON version holds multiple distributions, which becomes a list in `R`;
- The meta information in RIF is a little more elaborate, for example it can hold transformations for the horizontal or vertical axes. A back and forth transform between RIF-JSON would require some additional fields in the JSON format;
- There is an `interval` field in JSON that does not appear in RIF. My guess is that it is only used for labelling, and does not contain additional information over decimal age. If it does hold additional info, then the RIF need extended to support back-and-forth transforms.

I currently lack the time to work on the actual code to convert, but my impression thus far is that such conversion can very well be done.

**Comment by eatyourpeas** [comment]
@statist7 is a whizz with R. I am only just finding my feet with it. The interval field is actually now redundant - in the original .xls reference it was a column used to calculate decimal age and I wondered about doing that in the same way when converting to JSON. In the end we hardcoded the values.  If @statist7 wanted to keep that level of detail, as you say perhaps we could extend RIF to include it.

**Comment by statist7** [comment]
We absolutely do not need the `interval` field.

It would certainly be useful to expand the palette of reference formats that the API can handle, for import purposes.

**Comment by eatyourpeas** [comment]
I have made a first stab [here](https://github.com/rcpch/growth-references/tree/main/uk90/rif)
@stefvanbuuren I would be grateful if you could look over and make sure this is correct?
Can I also check nomenclature?
1. file names wgt and hgt reference height and weight, is that correct? Can I ask why not use the full word?
2. sex in the filename is referenced as boy/girl, but in the file itself as male/female
Are these recognised standards for growth reference naming? If not could we perhaps set some?
Finally, I see in your repo, you have readily converted 2006 references in rif format already. Would you be happy for us to host the same files?

**Comment by eatyourpeas** [comment]
This thread has not been active for over a month. .RIF implementation has been made for several references within this repository and it is agreed that this format should be included as well as JSON going forward.
