### ISSUE TITLE
Missing boys weight

### ISSUE THREAD

**Issue by blhardy** [rcpch/growth-references#4]
The txt file for boys weight is missing.

**Comment by pacharanero** [comment]
Sorry for the delay in replying - which file is missing? Can you specify a path please?

**Comment by pacharanero** [comment]
Actually, as part of some other work I noticed the missing file. Will review
https://github.com/rcpch/growth-references/tree/main/uk90/rif
There is a `uk-who_weight_girls.txt` but no boys equivalent, and it is a reference that should have a boys value.

**Comment by eatyourpeas** [comment]
Thanks for this @blhardy - could I ask what your use case is and why .txt format rather than .rif or .csv? My curiosity is allied to the other issue in this repository.

**Comment by EoinMcCarthy3** [comment]
Hi folks, hope all well. Just wondering if there was any update on this? I would love to get access to the boy's weights data, as I'm using it to make a tool for audit!

Kind regards

**Comment by eatyourpeas** [comment]
The data is all there in the spreadsheets already. It just has not been converted to the RIF format. We are open to pull requests if you wanted to do that. Note that if you are building a clinical tool, the data is licensed by MRC.

**Comment by EoinMcCarthy3** [comment]
Thank you very much, and duly noted. Perhaps I'm missing something, but I can't find the spreadsheet that corresponds to the weight values for boys (up to age), such as the data in (https://github.com/rcpch/growth-references/tree/main/uk90/rif)
/uk-who_weight_girls.txt)
Many thanks again for your time

**Comment by eatyourpeas** [comment]
It depends which reference you are after. If it is the UK-WHO reference then that is [here](https://github.com/rcpch/growth-references/blob/main/uk-who/UK_WHO_0_20_preterm.csv). Good luck with your project.

**Comment by EoinMcCarthy3** [comment]
Thank you very much for your help.
