### ISSUE TITLE
RIF files for UK WHO height/age distributions don't appear to be correct

### ISSUE THREAD

**Issue by whanrott** [rcpch/growth-references#5]
I think that there is an issue with the data in: https://raw.githubusercontent.com/rcpch/growth-references/main/uk90/rif/uk-who_height_girls.txt and https://raw.githubusercontent.com/rcpch/growth-references/main/uk90/rif/uk-who_height_boys.txt

The column 'M' appears to be median height, but this the values are the same for boys and girls.

It would also be useful to have a data description, to explain the LMS distribution values. It's not clear to me, as a non-clinical person. They appear to be:
- L Box-Cox transformation; 
- M Median height value;
- S  Generalized coefficient of variation

**Comment by pacharanero** [comment]
Thanks for reporting this discrepancy @whanrott. We will investigate and report back.
@eatyourpeas Could we look into this on our next call?

**Comment by eatyourpeas** [comment]
@whanrott thanks and sorry to be slow to respond.
You are correct that is what the LMS values represent. It is not clear to me what the best format to store these references in is, and actually this repository could use a bit of an overhaul.
Most colleagues are familiar with LMS references in .csv format but I have seen elsewhere an attempt to standardise them as a .rif format. I am less familiar with this but have had a go.
Maybe @statist7 could advise on the best format and guide on how best to organise the library we have?

**Comment by statist7** [comment]
There is clearly a problem with uk90 median height being the same for boys and girls.

The .rif format seems to be for images, so I'm unclear how it works with tabular data. Is there a problem with .csv format?

**Comment by whanrott** [comment]
There seem to be two issues here. The meaning of an LMS distribution might be clarified in the readme file. It seems standard in your field, but is unclear to me. The correctness of the data is a separate issue.

The RIF format for the data is just a fixed-width file (FWF). That is easily usable using the data analysis tools which I'm familiar with, and so hopefully isn't an issue.

**Comment by statist7** [comment]
I thought that the LMS method was explained elsewhere in the documentation, though I'm not sufficiently familiar with the site to say where.

**Comment by pacharanero** [comment]
There is some documentation here in the Growth Charts main documentation site, which explains what LMS are and how they work. If there's anything not clearly explained then feel free to continue to ask questions here and we can aim to update the documentation accordingly.

https://growth.rcpch.ac.uk/clinician/how-the-api-works/#the-lms-method

**Comment by eatyourpeas** [comment]
The RIF format stands for [reference interchange format](https://rdrr.io/github/growthcharts/centile/) and I think is being offered as a standard. I am not sure who developed it or how popular it is but thought I would try and convert the references we have. I may have made a mistake if the values are incorrect.

@statist7 - if this is not a format you are familiar with, should I remove these files and stick with .csv as you suggest?

**Comment by statist7** [comment]
TBH I don't have strong views on the format as long as the data are correct. I'm unclear why anyone would want to obtain the LMS values from the API anyway.

**Comment by pacharanero** [comment]
@eatyourpeas it has been pointed out to us again that the following two files are identical in content:
[rif/uk-who_bmi_boys.txt](https://github.com/rcpch/growth-references/blob/main/uk90/rif/uk-who_bmi_boys.txt)
[rif/uk-who_bmi_girls.txt](https://github.com/rcpch/growth-references/blob/main/uk90/rif/uk-who_bmi_girls.txt)

Also worth noting that they both have a `yname` value of `ofc` when it should be `bmi`.

How are these files produced? Presumably they are a standard format, generated from some upstream data artefact? If we have a procedure for creating new ones I can do this. Or we could just remove the RIF files if they are not adding any new information and are simply derived from upstream data.

### Related
https://github.com/rcpch/growth-references/issues/3
https://github.com/rcpch/growth-references/issues/4

**Comment by eatyourpeas** [comment]
I think remove the rif files
I think I added them a long time back as it's had been suggested elsewhere that it was a standard we should support
Same also for the .txt

**Comment by eatyourpeas** [comment]
Sorry to be slow with this. I have added links in the readme to documentation on the LMS method (thanks to @whanrott for noticing this), removed the .rif and .txt files as questionable accuracy in some of those files, and added the AAP trisomy reference.
